### ISSUE TITLE
tomogram ID filter does not work.

### ISSUE THREAD

**Issue by anchi2c** [chanzuckerberg/napari-cryoet-data-portal#17]
I put in 11, and it shows this:
<img width="367" alt="tomogram_id" src="https://github.com/chanzuckerberg/napari-cryoet-data-portal/assets/35783766/b21e9c76-2e7c-411a-81f6-a349a66192e9">

**Comment by andy-sweet** [comment]
Using the GraphQL client, there are no tomograms with ID 11.

For example, executing this makes `tomos` an empty list.

```python
from cryoet_data_portal import Client, Tomogram
client = Client()
tomos = list(Tomogram.find(client, [Tomogram.id == 11]))
```

**Comment by andy-sweet** [comment]
I guess we could be more explicit with messaging that no data was found though, so that the user knows nothing went wrong and that we just didn't find anything.
